// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartsTracker.Models;

#nullable disable

namespace PartsTracker.Migrations
{
    [DbContext(typeof(PartsContext))]
    [Migration("20250701035625_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartsTracker.Models.Part", b =>
                {
                    b.Property<string>("PartNumber")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastStockTake")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("integer");

                    b.HasKey("PartNumber");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            PartNumber = "P_001",
                            Description = "Screen with atleast 2.5 HDMI Ports",
                            LastStockTake = new DateTime(2025, 6, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationCode = "pta-2",
                            QuantityOnHand = 31
                        },
                        new
                        {
                            PartNumber = "P_002",
                            Description = "Mouse that is both wireless, and not",
                            LastStockTake = new DateTime(2025, 6, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationCode = "pta-1",
                            QuantityOnHand = 29
                        },
                        new
                        {
                            PartNumber = "P_003",
                            Description = "Keyboard with 16 additional keys",
                            LastStockTake = new DateTime(2025, 6, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationCode = "jhb-1",
                            QuantityOnHand = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
