// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartsTracker.Models;

#nullable disable

namespace PartsTracker.Migrations
{
    [DbContext(typeof(PartsContext))]
    [Migration("20250701034123_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartsTracker.Models.Part", b =>
                {
                    b.Property<string>("PartNumber")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastStockTake")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("integer");

                    b.HasKey("PartNumber");

                    b.ToTable("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
