version: '3.4'

services:
  partstracker:
    image: ${DOCKER_REGISTRY-}partstracker
    build:
      context: .
      dockerfile: PartsTracker/Dockerfile
    depends_on:
        db:
          condition: service_healthy
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: partsuser
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: parts
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U partsuser"]
        interval: 10s
        timeout: 5s
        retries: 5
